#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults
PROCESS_NAME="firefox"

check_container_initialized
liftoff

print_start "Starting xeyes"
export HOME="/data"
export DISPLAY=":1"
silent s6-setuidgid ${APP_USER} firefox

