#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="custom"

prepare_service

chown -f -R ${APP_USER}:${APP_USER} /data

## Copy over any custom files overtop of source
if [ -d "/assets/custom" ]; then
    print_warn "Detected Custom Source - Copying over to application"
    cp -R /assets/custom/* /
fi

## Execute Custom Scripts
if [ -d /assets/custom-scripts/ ] ; then
    print_warn "Found Custom Scripts to Execute"
    for f in $(find /assets/custom-scripts/ -name \*.sh -type f); do
        print_warn "Running Script ${f}"
        ${f}
    done
fi

liftoff