#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="custom"

prepare_service

chown -f -R ${APP_USER}:${APP_USER} /data

custom_files "${CONTAINER_CUSTOM_PATH}" /
custom_scripts

liftoff