#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults
PROCESS_NAME="xfvb"

check_container_initialized
check_service_initialized init
liftoff

print_start "Starting xvfb"
silent /usr/bin/Xvfb :1 -screen 0 ${RESOLUTION}
